### ISSUE TITLE
Consider also passing selected value into onValueChange

### ISSUE THREAD

**Issue by mathew-kurian** [talut/react-native-picker-module#1]
Currently, passes selected index which deviates from the general standard. Adding selected value to can improve the API a little.

Regardless, great library!

**Comment by talut** [comment]
Sorry for long waiting. My job/life schedule is so full 😄 If I'll found any time I'll look

**Comment by mathew-kurian** [comment]
No rush here. Just some feedback to improve the library. Currently using a workaround.

**Comment by mathew-kurian** [comment]
No rush here. Currently, I am using a workaround. But I appreciate your effort in addressing it.

**Comment by talut** [comment]
Solved: https://github.com/talut/react-native-picker-module/releases/tag/1.0.0
