### ISSUE TITLE
Android show problem

### ISSUE THREAD

**Issue by jonat75** [talut/react-native-picker-module#11]
When i use your sample code, everything works on Ios but on android there is an error:
null is not an object(evaluating'_reactNative.NativeModules.ReactNativePickerModule.show')

**Comment by talut** [comment]
Hi which version of React Native are you using?

**Comment by jonat75** [comment]
Hi, i use 0.59.8 version with expo sdk34

**Comment by talut** [comment]
I never used Expo but I think Expo not support  directly `react-native link` and this package is using NativeModules.

[https://docs.expo.io/versions/latest/introduction/faq/](
https://docs.expo.io/versions/latest/introduction/faq/)

- The most limiting thing about managed Expo projects is that you can't add in your own native modules without detaching and using ExpoKit. Continue reading the next question for a full explanation.
