### ISSUE TITLE
1.2.0 android not working

### ISSUE THREAD

**Issue by happylolonly** [talut/react-native-picker-module#12]
Hi, check, please android version.

![image](https://user-images.githubusercontent.com/18665326/64125015-401c1b00-cdb1-11e9-9d2b-9d3db535b703.png)

**Comment by talut** [comment]
Hi which version of React Native are you using? Do you use Expo? If you using RN <=v0.59 did you run react-native link?

**Comment by happylolonly** [comment]
Hey, I use these versions:
   ```
 "expo": "^33.0.0",
 "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz"
```

What do I need to do to fix it?

Thanks.

**Comment by talut** [comment]
@happylolonly Please look this issue/comment : https://github.com/talut/react-native-picker-module/issues/11#issuecomment-527102376
