### ISSUE TITLE
Bug:  java.lang.Double cannot be cast to java.lang.String 

### ISSUE THREAD

**Issue by qalqi** [talut/react-native-picker-module#15]
React Native Picker Module version `1.1.1` is crashing android app with the following error.

`java.lang.Double cannot be cast to java.lang.String`

Just running example like shared in README.md

Steps to produce the error
1) Click Show Language Picker
2) Pick a Language
3) Again click Show Language Picker
4) Crash

**Comment by talut** [comment]
Hi, sorry for late answer. This version is not supporting type cast. So you should cast your Double values to string. But I'll add this feature.

**Comment by hasanugr** [comment]
Hi I'm using v1.3.1 and I have same problem.


**Steps to produce the error**
1. Click Show Picker
2. Crash

**SS**
![image](https://user-images.githubusercontent.com/18167158/77061409-3bd0eb80-69eb-11ea-90e3-1106c2b1668b.png)
