### ISSUE TITLE
How to pass an array of objects instead of strings?

### ISSUE THREAD

**Issue by unigeniee** [talut/react-native-picker-module#2]
I have an array of objects like this
```
data: [
{name: 'option 1', value: 100},
{name: 'option 2', value: 101},
{name: 'option 3', value: 102},
{name: 'option 4', value: 103},
]
```
How to pass this kind of data in the Picker? And I can manage what to display?
Using an arrays of strings is a limitation
Thank you!

**Comment by talut** [comment]
Hi, package is not support objects. You should create new array with this object and pass this array to Picker. Right now I'm using like that too. But also I'm not liked this so I trying to change this behavior.

**Comment by nzrin** [comment]
When will you support object?
