### ISSUE TITLE
Undefined is not an object (evaluating 'this.pickerRef.show')

### ISSUE THREAD

**Issue by arshiuh** [talut/react-native-picker-module#20]
![992826C4-682D-420B-AE2A-782B5B7589F1](https://user-images.githubusercontent.com/47709508/69889305-1174ea00-12a5-11ea-89db-fc7b9ebfff6e.png)

`{this.pickerRef.show()}
            <ReactNativePickerModule
              pickerRef={e => (this.pickerRef = e)}
              selectedValue={this.state.selectedItem}
              title={'How many drinks did customer order?'}
              items={this.state.data}
              onDismiss={() => {
                console.log('onDismiss');
                this.props.navigation.goBack();
              }}
              onCancel={() => {
                console.log('Cancelled');
              }}
              onValueChange={(valueText, index) => {
                console.log('value: ', valueText);
                console.log('index: ', index);
                this.setState({
                  valueText: valueText,
                  selectedItem: index
                });
              }}
            />`

I am trying so that it doesn't execute in a `TouchableOpacity` but not sure if i am doing this right. I am following an example I found but it doesn't seem like its working.

![image](https://user-images.githubusercontent.com/47709508/69889383-729cbd80-12a5-11ea-842a-091eabe0f857.png)

**Comment by talut** [comment]
Hi, you shouldn't use `this.pickerRef.show()` as a child of in a component. You should call `this.pickerRef.show() like function. 'cause it's a function.  

```javascript
<Button title="Show Picker" onPress={()=>this.pickerRef.show()}/>
```

**Comment by arshiuh** [comment]
![image](https://user-images.githubusercontent.com/47709508/69907056-89fda880-1382-11ea-8b54-49a764f93872.png)

I am calling it in a function. Instead, I have moved it inside another function `handleBarCodeScanned`, when a barcode is scanned.

**Comment by arshiuh** [comment]
Why did you close it? You have not solved the problem.

**Comment by talut** [comment]
```
  pickerRef={e => this.pickerRef = e}
```

Write like that it'll solve your problem

**Comment by talut** [comment]
Is it in a class component right? 

The following code was taken from an active project.
```
import ReactNativePickerModule from "react-native-picker-module"

            <ReactNativePickerModule
              items={this.state.languages}
              cancelButton={Translation("CANCEL")}
              confirmButton={Translation("APPROVE")}
              pickerRef={e => (this.languagePicker = e)}
              value={selectedNativeLang === null ? null : selectedNativeLang}
              onValueChange={(value, index) => {
                this.changeNativeLanguage(index);
              }}
            />

```

```
this.languagePicker.show()
```

**Comment by arshiuh** [comment]
I am basically doing the same thing here but without `value=...`. The problem is `this.languagePicker.show()`. Yes the whole thing is in the class component, but I am not using new react native. I am using the latest Expo, which I believe is still on 0.58.

`import React from 'react';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';
import Constants from 'expo-constants';
import * as Permissions from 'expo-permissions';
import { BarCodeScanner } from 'expo-barcode-scanner';
import ReactNativePickerModule from 'react-native-picker-module';
import { createStackNavigator } from 'react-navigation-stack';
import firebase from 'firebase';

class ScannerScreen extends React.Component {
  state = {
    hasCameraPermission: null,
    scanned: false,
    valueText: undefined,
    selectedIndex: null,
    data: [
      '1 Drink',
      '2 Drinks',
      '3 Drinks',
      '4 Drinks',
      '5 Drinks',
      '6 Drinks',
      '7 Drinks',
      '8 Drinks',
      '9 Drinks',
      '10 Drinks'
    ]
  };

  async componentDidMount() {
    this.getPermissionsAsync();
  }

  getPermissionsAsync = async () => {
    const { status } = await Permissions.askAsync(Permissions.CAMERA);
    this.setState({ hasCameraPermission: status === 'granted' });
  };

  render() {
    const { hasCameraPermission, scanned } = this.state;

    if (hasCameraPermission === null) {
      return (
        <View style={styles.container}>
          <Text>Requesting for camera permission</Text>
        </View>
      );
    }
    if (hasCameraPermission === false) {
      return (
        <View style={styles.container}>
          <Text>
            No access to camera. Please go into your phone settings and allow
            StampApp to use your phone's camera.
          </Text>
        </View>
      );
    }
    return (
      <View style={styles.container}>
        <BarCodeScanner
          onBarCodeScanned={scanned ? undefined : this.handleBarCodeScanned}
          style={StyleSheet.absoluteFillObject}
          barCodeTypes={[BarCodeScanner.Constants.BarCodeType.qr]}
        />

        {scanned && (
          <>
            {/* Current: Error pops regarding this.pickerRef.show() */}

            <ReactNativePickerModule
              pickerRef={e => (this.pickerRef = e)}
              selectedValue={this.state.selectedItem}
              title={'How many drinks did customer order?'}
              items={this.state.data}
              onDismiss={() => {
                // Gets selectedValue (maybe index) to database to stamp card
                console.log('onDismiss');
                this.props.navigation.goBack();
              }}
              onCancel={() => {
                // Cancels transaction
                console.log('Cancelled');
              }}
              onValueChange={(valueText, index) => {
                console.log('value: ', valueText);
                console.log('index: ', index);
                this.setState({
                  valueText: valueText,
                  selectedItem: index
                });
              }}
            />
          </>
        )}
      </View>
    );
  }
  handleBarCodeScanned = ({ type, data }) => {
    // This is where it checks or adds stamp card to current user
    const storeID = firebase.auth().currentUser.uid;
    // Used this to name store... Need to make a permanent script to make displayName for stores
    // firebase.auth().currentUser.updateProfile({ displayName: 'Groundswell' });
    const storeName = firebase.auth().currentUser.displayName;
    const stampCardData = { storeName, stamps: 0 };
    console.log(storeID);
    console.log(data);
    console.log(type);
    const db = firebase.firestore();
    db.collection('users')
      .doc(data)
      .collection('stampcards')
      .doc(storeID)
      .set(stampCardData);
    this.setState({ scanned: true });
    this.pickerRef.show();
  };
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center'
  },
  picker: {
    backgroundColor: '#fafafa',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 200
  },
  warningText: {
    fontSize: 16,
    textAlign: 'center'
  }
});

export default ScannerScreen;
`

**Comment by talut** [comment]
@arshiuh Hi I understood the problem. You are using Expo so you can't use this package. 'cause this package is using native module. 

https://stackoverflow.com/a/44978581/3366361

**Comment by talut** [comment]
@arshiuh I'm closing issue if this answer is enough
