### ISSUE TITLE
[FEATURE REQUEST] How to use Image next to the Text in Picker ?

### ISSUE THREAD

**Issue by choudharyjji** [talut/react-native-picker-module#23]
Hello Developer, 

First of all thanks for this beautiful module. I would like to ask you that is it possible to use custom image next to the text ?? 

Please let me know if it is possible. Thanks

**Comment by talut** [comment]
Hi thanks :) Right now package not have this feature. But I'm thinking rewrite this package with new and more features.

**Comment by choudharyjji** [comment]
@talut Hi, Thanks for replying. I will wait for the update then :)

**Comment by choudharyjji** [comment]
@talut  is this e-mail is active : hi@talut.dev ??

**Comment by talut** [comment]
> @talut is this e-mail is active : [hi@talut.dev](mailto:hi@talut.dev) ??

Hi, yes I received your e-mail and replied two days ago

**Comment by choudharyjji** [comment]
@talut  Thanks buddy!

**Comment by talut** [comment]
v1.3.0 Released with this feature.
