### ISSUE TITLE
Cannot find symbol error.

### ISSUE THREAD

**Issue by choudharyjji** [talut/react-native-picker-module#24]
**node_modules\react-native-picker-module\android\src\main\java\com\taluttasgiran\pickermodule\RNSpinnerAdapter.java:76**: error: cannot find symbol
        ImageView imageView = holder.linearLayout.findViewById(R.id.item_image);
                                                                   ^
  symbol:   variable item_image
  location: class id
1 error

FAILURE: Build failed with an exception.

**Comment by talut** [comment]
Hi, please update to v1.3.1 and reinstall app.
