### ISSUE TITLE
Use native animations

### ISSUE THREAD

**Issue by dpyeates** [talut/react-native-picker-module#27]
Please can you use the native driver for all animations. Not using the native drivers in React Native 0.62 and above gives a YellowBox warning.

```
            Animated.timing(this.state.animation, {
              toValue: 1,
              duration: ios.duration,
              useNativeDriver: true <---- add this
            }).start();
```

**Comment by talut** [comment]
https://github.com/talut/react-native-picker-module/pull/28 [MERGED]

I'll release a new version ASAP
