### ISSUE TITLE
Question: Usage in class

### ISSUE THREAD

**Issue by dpyeates** [talut/react-native-picker-module#30]
Hi there,

I have upgraded to the latest version and I note that the example now uses hooks.

I am using the component within a class

```
render(): React.Node {
    return (
      <ReactNativePickerModule
        pickerRef={(e) => {
          this._picker = e;
        }}
        value={this.props.selectedIndex}
        title={this.props.title}
        items={this.props.options}
        onDismiss={() => {}}
        onCancel={() => {}}
        onValueChange={(valueText, index) => {
          this.props.onPress(index);
        }}
      />
    );
  }
```

Whereas as this used to work, I now do not get _picker getting initialised and hence elsewhere in my class where I go to display the picker, I get nothing.

What is the correct usage for this component within a class now?

**Comment by talut** [comment]
Hi,  I added new example for class components. Please check the link.

https://github.com/talut/react-native-picker-module#class-component-example

**Comment by ciaoamigoschat** [comment]
When I move the picker the following warning is shown:
"State updates from the useState () and useReducer () Hooks don't support the second callback argument."
How can I solve it?

**Comment by talut** [comment]
@ciaoamigoschat  Hi, do you using class component and can you share your code snippet?

**Comment by ciaoamigoschat** [comment]
Yes, I'm using class component...

` <ReactNativePickerModule
          pickerRef={this.pickerRef}
          value={this.returncountid(dati,this.state.selectedItem)}
          title={altTitle? altTitle : title} 
          items={this.filterdati(dati)}
          confirmButton={"Conferma"}
          cancelButton={"Annulla"}
          onDismiss={()=>{console.log("onDismiss")}}
          onCancel={()=>{console.log('Cancelled')}}
          onValueChange={valueText => {this.onChange(valueText)}}
          />`

**Comment by talut** [comment]
@ciaoamigoschat 

```
import React from "react"
import { SafeAreaView, Text, Button } from "react-native"
import ReactNativePickerModule from "react-native-picker-module"
const dataset_1 = [1, 2, "Java", "Kotlin", "C++", "C#", "PHP"]
const dataset = [
  {
    value: 101,
    label: "Javascript",
  },
  {
    value: "golang_101",
    label: "Go",
  },
  {
    value: "kotlin_dsl",
    label: "Kotlin",
  },
  {
    value: "java_101",
    label: "Java",
  },
  {
    value: "cplusplus",
    label: "C++",
  },
  {
    value: "csharp_201",
    label: "C#",
  },
  {
    value: "php_201",
    label: "PHP",
  },
]
class App extends React.Component {
  constructor(props) {
    super(props)
    this.pickerRef = React.createRef()
    this.state = {
      value: null,
    }
  }
  render() {
    return (
      <>
        <SafeAreaView>
          <Button title="Select a language" onPress={() => this.pickerRef.current.show()} />
          <Text>Selected Item Text: {this.state.value}</Text>
        </SafeAreaView>
        <ReactNativePickerModule
          pickerRef={this.pickerRef}
          value={this.state.value}
          title={"Select a language"}
          items={dataset_1}
          selectedColor="#FC0"
          onCancel={() => {
            console.log("Cancelled")
          }}
          onValueChange={value => {
            this.setState({
              value: value,
            })
          }}
        />
      </>
    )
  }
}
export default App

```

Would you try this example. I'm not getting any warning. (BTW; onDismiss is removed.)

**Comment by dpyeates** [comment]
For info, the example code you posted initially worked for me, thank you.
