### ISSUE TITLE
Android bug "Cannot read property `substr` of undefined "

### ISSUE THREAD

**Issue by NetPumi2** [talut/react-native-picker-module#32]
Hi i just jump on version 2.0.1 and ios is fine all works bud android have this error every time when I use `pickerRef.current.show();`

this is my code: 
```
...
const pickerRef: any = useRef(undefined); 

//button onPress 
  const onShowLanguagePicker = () => {
    console.log('PICKER', pickerRef);
    if (pickerRef.current) {
       pickerRef.current.show();
    }
  };

        <ReactNativePickerModule
          items={availableLanguageList}
          pickerRef={pickerRef}
          title={I18n.t('screens.settings.selectLanguage')}
          value={selectedValueIndex}
          onValueChange={onLanguageSelect}
        />
...
```
ios works fine  .... if I console log ref there are two functions `hide` and `show` and if i am trying to use it on android i get this:   
<img width="329" alt="Screenshot 2020-07-08 at 09 39 57" src="https://user-images.githubusercontent.com/5843275/86891400-0e758e00-c0ff-11ea-91b3-714159777a96.png">
<img width="331" alt="Screenshot 2020-07-08 at 09 47 38" src="https://user-images.githubusercontent.com/5843275/86892150-27cb0a00-c100-11ea-9c84-8a9b581930f5.png">

and side question: How can I create a type for ref?

**Comment by CezarCobuz** [comment]
Same for me, only for Android @talut would you be so kind to investigate this when you have the time?

**Comment by talut** [comment]
Hi, @NetPumi2  % @CezarCobuz I create new project and tested like https://github.com/talut/react-native-picker-module#usage-with-hooks and I didn't encounter with any error. 

can you share more info?

**Comment by CezarCobuz** [comment]
ERROR: TypeError: undefined is not an object (evaluating 'input.substr')

**Comment by talut** [comment]
Issue solved. Please check v2.0.2
