### ISSUE TITLE
Request: override confirm to force select

### ISSUE THREAD

**Issue by xstead** [talut/react-native-picker-module#34]
### New Feature Request

Add **confirmButtonAlwaysEnabled** boolean prop and disable the confirm button _disabled_ mode when set **true**. (value are eq. with selectedValue)

_for ex.:_

`
  confirmButtonAlwaysEnabled?: boolean
`

```
...
let isConfirmDisabled = (confirmButtonAlwaysEnabled) ? false : (value === selectedValue);
...

...
        <TouchableOpacity
          activeOpacity={0.9}
          disabled={isConfirmDisabled}
          onPress={() => {
            onValueChange(selectedValue)
            setIsVisible(false)
          }}
          style={[styles.confirmButtonView, confirmButtonStyle]}>
          <Text
            style={[
              styles.confirmButtonText,
              isConfirmDisabled ? confirmButtonDisabledTextStyle : confirmButtonEnabledTextStyle,
            ]}>
            {confirmButton}
          </Text>
        </TouchableOpacity>
...

```

**Comment by talut** [comment]
Hi, right now I don't have any time for feature. Only I'm fixing issue. But at future I'll handle this.

**Comment by nguyenvanquan7826** [comment]
Hi, During wait @talut fix it, you can use in my fix here: https://github.com/nguyenvanquan7826/react-native-picker-module

I can not create branch and pull request in this project, so I fork and edit.

**Comment by talut** [comment]
**v2.0.6 Released**
