### ISSUE TITLE
@react-native-community/picker is deprecated and no longer available

### ISSUE THREAD

**Issue by giacomoalonzi** [talut/react-native-picker-module#52]
Hello there, the @react-native-community/picker, the library that your package use is no longer available, so when I try to build, this dependency is missed. I've tried to force the installation, but I get "Invariant Violation: Tried to register two views with the same name RNCPicker #403"
the issue is described here https://github.com/lawnstarter/react-native-picker-select/issues/403

thank you!

**Comment by talut** [comment]
Hey @giacomoalonzi  thanks for issue. I'm checking right now. And I think I forgot to change picker library that I used for IOS implementation. 

ASAP I'll solve this problem. Thx.

**Comment by giacomoalonzi** [comment]
> Hey @giacomoalonzi thanks for issue. I'm checking right now. And I think I forgot to change picker library that I used for IOS implementation.
> 
> ASAP I'll solve this problem. Thx.

Thank you man! :)
