### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by virtualLast** [talut/react-native-picker-module#6]
**undefined is not an object (evaluating '_reactNative.NativeModules.ReactNativePickerModule.show))**
Above is the error I receive on android simulator when clicking on the button to launch the picker. Code implementation is below.

Latest version of Android Studio using Pixel 2XL with Oreo

`
<Text style={textLabelStyles}>Categories</Text>
            <ReactNativePickerModule
              pickerRef={e => (this.categoryPicker = e)}
              value={pickerValues.indexOf(prodCategories)}
              title="Choose product category"
              items={pickerValues}
              onValueChange={index =>
                this.setState({
                  prodCategories: pickerValues[index],
                })
              }
            />
            <TouchableOpacity
              onPress={() => {
                this.categoryPicker.show();
              }}
            >
              <Text>Choose category</Text>
            </TouchableOpacity>
`

**Comment by talut** [comment]
Hi I'm very sorry for late answer. But I think your problem is defining pickerRef. If you define pickerRef like `pickerRef={e => this. categoryPicker = e}` it'll work.
