### ISSUE TITLE
Add `onCancel` event handler.

### ISSUE THREAD

**Issue by souvik-ghosh** [talut/react-native-picker-module#7]
I really like this library, but, not having a `onCancel` event handler is stopping me to use it. I saw that it can be easily implemented. I can open a PR if you want. Please look into this asap.
again, thanks for building this library.

**Comment by talut** [comment]
Hi, if I'm correct you're wanting a callback for cancel button?

**Comment by souvik-ghosh** [comment]
Yes, exactly! thats what I want. Thanks for the quick response.

**Comment by talut** [comment]
Hey, @souvik-ghosh I just added this feature to package. If it anything wrong let me know.

[https://github.com/talut/react-native-picker-module#version-111](https://github.com/talut/react-native-picker-module#version-111)

**Comment by souvik-ghosh** [comment]
@talut, Thank you so much man! Keep up the good work.
