### ISSUE TITLE
when no value is provided, have to scroll down and back up to select and confirm the first item

### ISSUE THREAD

**Issue by souvik-ghosh** [talut/react-native-picker-module#8]

**Comment by souvik-ghosh** [comment]
to

**Comment by fahadibrahimbutt** [comment]
I am having the same issue.

**Comment by pjcaro** [comment]
@souvik-ghosh Did you find any solution?

**Comment by nguyenvanquan7826** [comment]
Hi, During wait @talut  fix it, you can use in my fix here: https://github.com/nguyenvanquan7826/react-native-picker-module

I can not create branch and pull request in this project, so I fork and edit.
